services:

  backend:
    image: johnbrush/suprvisionai:backend-latest
    pull_policy: always
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MONGO_DB_URI: ${MONGO_DB_URI}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AGENT_IMAGE_NAME: ${AGENT_IMAGE_NAME}
      BUILD_NUMBER: ${BUILD_NUMBER}
      AWS_REGION: ${AWS_REGION}
      AWS_USER_POOL_ID: ${AWS_USER_POOL_ID}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
    networks:
      - suprvision-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  agent:
    image: johnbrush/suprvisionai:agent-latest
    pull_policy: always
    build:
      context: .
      dockerfile: agent/Dockerfile
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SCREEN_GEOMETRY: ${SCREEN_GEOMETRY}
      VIEWPORT_SIZE: ${VIEWPORT_SIZE}
    networks:
      - suprvision-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gateway:
    image: johnbrush/suprvisionai:gateway-latest
    pull_policy: always
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    depends_on:
      - backend
    networks:
      - suprvision-network

  frontend:
    image: johnbrush/suprvisionai:frontend-latest
    pull_policy: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - suprvision-network

  ingress:
    image: johnbrush/suprvisionai:ingress-latest
    pull_policy: always
    build:
      context: ./ingress
      dockerfile: Dockerfile
    container_name: ingress
    ports:
      - "${INGRESS_PORT}:80"
    depends_on:
      - gateway
      - frontend
    networks:
      - suprvision-network

networks:
  suprvision-network:
    name: suprvision-network
    driver: bridge